name: check.yml
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    name: Check code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.0

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl1 \
            libxcb-cursor0 \
            libxkbcommon-x11-0 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-randr0 \
            libxcb-render-util0 \
            libxcb-shape0 \
            libxcb-xfixes0 \
            libxcb-xinerama0 \
            zip \
            clang \
            ccache

      - name: Install dependencies
        env:
          UV_INDEX_URL: https://pypi.org/simple
          UV_HTTP_TIMEOUT: "120"
          UV_HTTP_RETRIES: "5"
        run: |
          uv sync --group build --group lint

      - name: Check
        run: |
          bash ./script/test.sh
